name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
jobs:
  generate-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.9"
      - name: Run Python script to generate file
        run: |
          python app.py
      - name: Upload generated input file as artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: input.json
          path: |
            test/input.json
      - name: Download the input.json file
        uses: actions/download-artifact@v4.1.9
        with:
          name: input.json
          path: ./test
      - name: Run Python script to generate output file
        run: |
          python test.py
      - name: Upload generated output file as artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: output.xml
          path: |
            test/output.xml
      - name: Push to new branch and create pull request
        run: |
          git config --global user.name "Vicky-kr"
          git config --global user.email "Biki-Kumar.BikiKumar@shell.com"
          git pull origin $branch_name
          git checkout -b test/auto-test-generation
          git add .
          git commit -m "Auto generated test file"
          git pull
          git push origin test/auto-test-generation
          gh pr create --title "Automated Update" --body "This PR adds the latest files" --base $branch_name --head "test/auto-test-generation"
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
      - name: Print Confirmation message
        run: echo "Files have been successfully uploaded to the artifact store."
